stages:
  - build
  - release
  - deploy

variables:
  PROJECT_NAME: "ArupReleases"
  GITHUB_REPOSITORY: "tobynott80/ArupReleases"
  # RELEASE_NOTES_FILE: "README.md"

before_script:
  - echo "Starting CI/CD Pipeline..."

build_project:
  stage: build
  script:
    # Any future build steps we might need
    - echo "Project built successfully."
  artifacts:
    paths:
      - ./
  only:
    - main

create_gitlab_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: "v0.$CI_PIPELINE_IID" # The version is incremented per pipeline.
    description: "v0.$CI_PIPELINE_IID"
    ref: "$CI_COMMIT_SHA" # The tag is created from the pipeline SHA.

create_github_release:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl jq
  script:
    - echo "Packaging release..."
    - tar -czvf ${PROJECT_NAME}.tar.gz ./
    - echo "Creating release on GitHub..."
    - >
      curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/releases
      -H "Authorization: token $GITHUB_Key"
      -H "Content-Type: application/json"
      -d "{
        \"tag_name\": \"v$(date +%Y%m%d%H%M%S)\",
        \"target_commitish\": \"main\",
        \"name\": \"Release $(date +%Y-%m-%d %H:%M:%S)\",
        \"body\": \"Automated release generated by GitLab CI.\",
        \"draft\": false,
        \"prerelease\": false
      }"
    - >
      RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_Key" "https://api.github.com/repos/tobynott80/ArupReleases/releases" | jq '[.[] | {id, published_at}] | sort_by(.published_at) | reverse | .[0].id')
    - >
      curl -L
      -X POST
      -H "Accept: application/vnd.github+json"
      -H "Authorization: token $GITHUB_Key"
      -H "X-GitHub-Api-Version: 2022-11-28"
      -H "Content-Type: application/octet-stream"
      "https://uploads.github.com/repos/tobynott80/ArupReleases/releases/$RELEASE_ID/assets?name=application.zip"
      --data-binary "@${PROJECT_NAME}.tar.gz"
    - echo "Release created successfully."
  only:
    - main
