stages:
  - build
  - deploy

variables:
  PROJECT_NAME: "ArupReleases"
  GITHUB_REPOSITORY: "tobynott80/ArupReleases"
  # RELEASE_NOTES_FILE: "README.md"

before_script:
  - echo "Starting CI/CD Pipeline..."

build_project:
  stage: build
  script:
    # Any future build steps we might need
    - echo "Project built successfully."
  artifacts:
    paths:
      - ./
  only:
    - main

create_github_release:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Packaging release..."
    # Replace the following line with commands to package your project (e.g., zip, tar)
    - tar -czvf ${PROJECT_NAME}.tar.gz ./
    - echo "Creating release on GitHub..."
    - >
      curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/releases
      -H "Authorization: token $GITHUB_Key"
      -H "Content-Type: application/json"
      -d "{
        \"tag_name\": \"v$(date +%Y%m%d%H%M%S)\",
        \"target_commitish\": \"main\",
        \"name\": \"Release $(date +%Y-%m-%d %H:%M:%S)\",
        \"body\": \"Automated release generated by GitLab CI.\",
        \"draft\": false,
        \"prerelease\": false
      }"
    - echo "Release created successfully."
  only:
    - main
